In [50]:
import pandas as pd

In [51]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [52]:
import numpy as np

In [53]:
from path import Path

In [54]:
file_path = "iris.csv"
iris_df = pd.read_csv(file_path)
iris_df.head()

sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [55]:
new_iris_df = iris_df.drop(['class'], axis=1)
new_iris_df.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [56]:
output_file_path = "new_iris_data.csv"
new_iris_df.to_csv(output_file_path, index=False)

In [57]:
file_path = "shopping_data.csv"
df_shopping = pd.read_csv(file_path, encoding="ISO-8859-1")
df_shopping.head(5)

CustomerID Card Member   Age  Annual Income  Spending Score (1-100)
0           1         Yes  19.0          15000                    39.0
1           2         Yes  21.0          15000                    81.0
2           3          No  20.0          16000                     6.0
3           4          No  23.0          16000                    77.0
4           5          No  31.0          17000                    40.0

In [58]:
# Columns
df_shopping.columns

Index(['CustomerID', 'Card Member', 'Age', 'Annual Income',
       'Spending Score (1-100)'],
      dtype='object')

In [59]:
df_shopping.dtypes

CustomerID                  int64
Card Member                object
Age                       float64
Annual Income               int64
Spending Score (1-100)    float64
dtype: object

In [60]:
for column in df_shopping.columns:
    print(f"Column {column} has {df_shopping[column].isnull().sum()}null values")

Column CustomerID has 0null values
Column Card Member has 2null values
Column Age has 2null values
Column Annual Income has 0null values
Column Spending Score (1-100) has 1null values


In [61]:
# Drop null rows
df_shopping = df_shopping.dropna()

In [62]:
print(f"Duplicate entries: {df_shopping.duplicated().sum()}")

Duplicate entries: 0


In [63]:
df_shopping.drop(columns=["CustomerID"], inplace=True)
df_shopping.head()

Card Member   Age  Annual Income  Spending Score (1-100)
0         Yes  19.0          15000                    39.0
1         Yes  21.0          15000                    81.0
2          No  20.0          16000                     6.0
3          No  23.0          16000                    77.0
4          No  31.0          17000                    40.0

In [64]:
def change_string(member):
    if member == "Yes":
        return 1
    else:
        return 0
    
df_shopping["Card Member"] = df_shopping["Card Member"].apply(change_string)
df_shopping.head()

Card Member   Age  Annual Income  Spending Score (1-100)
0            1  19.0          15000                    39.0
1            1  21.0          15000                    81.0
2            0  20.0          16000                     6.0
3            0  23.0          16000                    77.0
4            0  31.0          17000                    40.0

In [65]:
df_shopping["Annual Income"] = df_shopping["Annual Income"] / 1000
df_shopping.head()

Card Member   Age  Annual Income  Spending Score (1-100)
0            1  19.0           15.0                    39.0
1            1  21.0           15.0                    81.0
2            0  20.0           16.0                     6.0
3            0  23.0           16.0                    77.0
4            0  31.0           17.0                    40.0

In [66]:
# Saving cleaned data
file_path = "shopping_data_cleaned.csv"
df_shopping.to_csv(file_path, index=False)

In [122]:
import pandas as pd
import plotly.express as px
import hvplot.pandas
from sklearn.cluster import KMeans

In [68]:
file_path = "new_iris_data.csv"
df_iris = pd.read_csv(file_path)
df_iris.head(10)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4
6           4.6          3.4           1.4          0.3
7           5.0          3.4           1.5          0.2
8           4.4          2.9           1.4          0.2
9           4.9          3.1           1.5          0.1

In [70]:
model = KMeans(n_clusters=3, random_state=5)
model

KMeans(n_clusters=3, random_state=5)

In [71]:
# Fitting model
model.fit(df_iris)

KMeans(n_clusters=3, random_state=5)

In [72]:
# Get the predictions
predictions = model.predict(df_iris)
print(predictions)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 2 2 2 0 2 2 2 2
 2 2 0 0 2 2 2 2 0 2 0 2 0 2 2 0 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 2
 2 0]


In [73]:
# Add a new class column to the df_iris
df_iris["class"] = model.labels_
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width  class
0           5.1          3.5           1.4          0.2      1
1           4.9          3.0           1.4          0.2      1
2           4.7          3.2           1.3          0.2      1
3           4.6          3.1           1.5          0.2      1
4           5.0          3.6           1.4          0.2      1

In [74]:
import plotly.express as px
import hvplot.pandas

In [75]:
# Create a scatterplot of df_iris
df_iris.hvplot.scatter(x="sepal_length", y="sepal_width", by="class")

:NdOverlay   [class]
   :Scatter   [sepal_length]   (sepal_width)

In [78]:
fig = px.scatter_3d(
    df.iris,
    x="petal_width",
    y="sepal_length",
    z="petal_length",
    color="class",
    symbol="class", 
    size="sepal_width",
    width=800,
)
fig.update_layout(legend=dict(x=0, y=1))
fig.show()

NameError: name 'df' is not defined

In [79]:
# Plotting the clusters with three features
fig = px.scatter_3d(df_iris, x="petal_width", y="sepal_length", z="petal_length", color="class", symbol="class", size="sepal_width",width=800)
fig.update_layout(legend=dict(x=0,y=1))
fig.show()

In [80]:
# Initial imports
import pandas as pd
from sklearn.cluster import KMeans
import plotly.express as px
import hvplot.pandas

In [81]:
# Load data
file_path = "shopping_data_cleaned.csv"
df_shopping = pd.read_csv(file_path)
df_shopping.head(10)

Card Member   Age  Annual Income  Spending Score (1-100)
0            1  19.0           15.0                    39.0
1            1  21.0           15.0                    81.0
2            0  20.0           16.0                     6.0
3            0  23.0           16.0                    77.0
4            0  31.0           17.0                    40.0
5            0  22.0           17.0                    76.0
6            0  35.0           18.0                     6.0
7            0  23.0           18.0                    94.0
8            1  64.0           19.0                     3.0
9            0  30.0           19.0                    72.0

In [82]:
df_shopping.hvplot.scatter(x="Annual Income", y="Spending Score (1-100)")

:Scatter   [Annual Income]   (Spending Score (1-100))

In [83]:
# Function to cluster and plot dataset
def test_cluster_amount(df, clusters):
    model = KMeans(n_clusters=clusters, random_state=5)
    model

    # Fitting model
    model.fit(df)

    # Add a new class column to df_iris
    df["class"] = model.labels_

In [84]:
test_cluster_amount(df_shopping, 2)
df_shopping.hvplot.scatter(x="Annual Income", y="Spending Score (1-100)", by="class")

:NdOverlay   [class]
   :Scatter   [Annual Income]   (Spending Score (1-100))

In [85]:
fig = px.scatter_3d(
    df_shopping,
    x="Annual Income",
    y="Spending Score (1-100)",
    z="Age",
    color="class",
    symbol="class",
    width=800,
)
fig.update_layout(legend=dict(x=0, y=1))
fig.show()

In [86]:
# Initial imports
import pandas as pd
from sklearn.cluster import KMeans
import plotly.express as px
import hvplot.pandas

In [87]:
# Loading data
file_path = "new_iris_data.csv"
df_iris = pd.read_csv(file_path)

df_iris.head(10)

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2
5           5.4          3.9           1.7          0.4
6           4.6          3.4           1.4          0.3
7           5.0          3.4           1.5          0.2
8           4.4          2.9           1.4          0.2
9           4.9          3.1           1.5          0.1

In [88]:
inertia = []
k = list(range(1, 11))

In [89]:
# Looking for the best K
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(df_iris)
    inertia.append(km.inertia_)

In [90]:
# Define a DataFrame to plot the Elbow Curve using hvPlot
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", title="Elbow Curve", xticks=k)

:Curve   [k]   (inertia)

In [93]:
# Initial imports
import pandas as pd
from sklearn.cluster import KMeans
import plotly.express as px
import hvplot.pandas

In [94]:
# Load data
file_path = "shopping_data_cleaned.csv"
df_shopping = pd.read_csv(file_path)
df_shopping.head(10)

Card Member   Age  Annual Income  Spending Score (1-100)
0            1  19.0           15.0                    39.0
1            1  21.0           15.0                    81.0
2            0  20.0           16.0                     6.0
3            0  23.0           16.0                    77.0
4            0  31.0           17.0                    40.0
5            0  22.0           17.0                    76.0
6            0  35.0           18.0                     6.0
7            0  23.0           18.0                    94.0
8            1  64.0           19.0                     3.0
9            0  30.0           19.0                    72.0

In [95]:
inertia = []
k = list(range(1, 11))

# Calculate the inertia for the range of K values
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(df_shopping)
    inertia.append(km.inertia_)

In [96]:
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")

:Curve   [k]   (inertia)

In [97]:
def get_clusters(k, data):
    # Create a copy of the DataFrame
    data = data.copy()

    # Initialize the K-Means model
    model = KMeans(n_clusters=k, random_state=0)

    # Fit the model
    model.fit(data)

    # Predict clusters
    predictions = model.predict(data)

    # Create return DataFrame with predicted clusters
    data["class"] = model.labels_

    return data

In [98]:
five_clusters = get_clusters(5, df_shopping)
five_clusters.head()

Card Member   Age  Annual Income  Spending Score (1-100)  class
0            1  19.0           15.0                    39.0      0
1            1  21.0           15.0                    81.0      4
2            0  20.0           16.0                     6.0      0
3            0  23.0           16.0                    77.0      4
4            0  31.0           17.0                    40.0      0

In [99]:
six_clusters = get_clusters(6, df_shopping)
six_clusters.head()

Card Member   Age  Annual Income  Spending Score (1-100)  class
0            1  19.0           15.0                    39.0      5
1            1  21.0           15.0                    81.0      4
2            0  20.0           16.0                     6.0      5
3            0  23.0           16.0                    77.0      4
4            0  31.0           17.0                    40.0      5

In [100]:
five_clusters.hvplot.scatter(x="Annual Income", y="Spending Score (1-100)", by="class")

:NdOverlay   [class]
   :Scatter   [Annual Income]   (Spending Score (1-100))

In [101]:
# Plot the 3D-scatter with x="Annual Income", y="Spending Score (1-100)" and z="Age"
fig = px.scatter_3d(
    five_clusters,
    x="Age",
    y="Spending Score (1-100)",
    z="Annual Income",
    color="class",
    symbol="class",
    width=800,
)
fig.update_layout(legend=dict(x=0, y=1))
fig.show()

In [102]:
six_clusters.hvplot.scatter(x="Annual Income", y="Spending_Score (1-100)", by="class")

DataError: Supplied data does not contain specified dimensions, the following dimensions were not found: ['Spending_Score (1-100)']

PandasInterface expects tabular data, for more information on supported datatypes see http://holoviews.org/user_guide/Tabular_Datasets.html

In [46]:
# Plotting the 3D-Scatter with x="Annual Income", y="Spending Score (1-100)" and z="Age"
fig = px.scatter_3d(
    six_clusters,
    x="Age",
    y="Spending Score (1-100)",
    z="Annual Income",
    color="class",
    symbol="class",
    width=800,
)
fig.update_layout(legend=dict(x=0, y=1))
fig.show()

In [103]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import hvplot.pandas

In [104]:
file_path = "new_iris_data.csv"
df_iris = pd.read_csv(file_path)
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [106]:
iris_scaled = StandardScaler().fit_transform(df_iris)
print(iris_scaled[0:5])

[[-0.90068117  1.03205722 -1.3412724  -1.31297673]
 [-1.14301691 -0.1249576  -1.3412724  -1.31297673]
 [-1.38535265  0.33784833 -1.39813811 -1.31297673]
 [-1.50652052  0.10644536 -1.2844067  -1.31297673]
 [-1.02184904  1.26346019 -1.3412724  -1.31297673]]


In [107]:
# Initialize PCA model
pca = PCA(n_components=2)

In [108]:
# Get two principal components for the iris data.
iris_pca = pca.fit_transform(iris_scaled)

In [109]:
df_iris_pca = pd.DataFrame(
    data=iris_pca, columns=["principal component 1", "principal component 2"]
)
df_iris_pca.head()

principal component 1  principal component 2
0              -2.264542               0.505704
1              -2.086426              -0.655405
2              -2.367950              -0.318477
3              -2.304197              -0.575368
4              -2.388777               0.674767

In [110]:
pca.explained_variance_ratio_

array([0.72770452, 0.23030523])

In [111]:
# Find the best value for K
inertia = []
k = list(range(1, 11))

# Calculate the inertia for the range of K values
for i in k:
    km = KMeans(n_clusters=i, random_state=0)
    km.fit(df_iris_pca)
    inertia.append(km.inertia_)

# Create the elbow curve
elbow_data = {"k": k, "inertia": inertia}
df_elbow = pd.DataFrame(elbow_data)
df_elbow.hvplot.line(x="k", y="inertia", xticks=k, title="Elbow Curve")

:Curve   [k]   (inertia)

In [112]:
# Initialize the K-means model
model = KMeans(n_clusters=3, random_state=0)

# Fit the model
model.fit(df_iris_pca)

# Predict clusters
predictions = model.predict(df_iris_pca)

# Add the predicted class columns
df_iris_pca["class"] = model.labels_
df_iris_pca.head()

principal component 1  principal component 2  class
0              -2.264542               0.505704      0
1              -2.086426              -0.655405      0
2              -2.367950              -0.318477      0
3              -2.304197              -0.575368      0
4              -2.388777               0.674767      0

In [113]:
df_iris_pca.hvplot.scatter(
    x="principal component 1",
    y="principal component 2",
    hover_cols=["class"],
    by="class",
)

:NdOverlay   [class]
   :Scatter   [principal component 1]   (principal component 2,class)

In [114]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import AgglomerativeClustering
import hvplot.pandas

In [115]:
file= "new_iris_data.csv"
df_iris = pd.read_csv(file)
df_iris.head()

sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [116]:
import plotly.figure_factory as ff

In [117]:
# Create the dendrogram
fig = ff.create_dendrogram(df_iris_pca, color_threshold=0)
fig.update_layout(width=800, height=500)
fig.show()

In [118]:
agg = AgglomerativeClustering(n_clusters=3)
model = agg.fit(df_iris_pca)

In [119]:
df_iris_pca["class"] = model.labels_
df_iris_pca.head

<bound method NDFrame.head of      principal component 1  principal component 2  class
0                -2.264542               0.505704      0
1                -2.086426              -0.655405      0
2                -2.367950              -0.318477      0
3                -2.304197              -0.575368      0
4                -2.388777               0.674767      0
..                     ...                    ...    ...
145               1.870522               0.382822      2
146               1.558492              -0.905314      1
147               1.520845               0.266795      2
148               1.376391               1.016362      2
149               0.959299              -0.022284      1

[150 rows x 3 columns]>

In [121]:
df_iris_pca.hvplot.scatter(
    x="principal component 1",
    y="principal component 2", 
    hover_cols=["class"], 
    by="class"
)

:NdOverlay   [class]
   :Scatter   [principal component 1]   (principal component 2,class)